/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);

uint32_t current_task = 0;

uint32_t task_stacks[MAX_TASK] =
								{
								T1_STACK_START,
								T2_STACK_START,
								T3_STACK_START,
								T4_STACK_START
								};
uint32_t task_handlers[MAX_TASK] =
								{
								(uint32_t)task1_handler,
								(uint32_t)task2_handler,
								(uint32_t)task3_handler,
								(uint32_t)task4_handler
								};

uint32_t psp_top_of_stack[MAX_TASK] =
								{
								T1_STACK_START,
								T2_STACK_START,
								T3_STACK_START,
								T4_STACK_START
								};


int main(void)
{

	enable_all_exceptions();
	task1_handler();
    /* Loop forever */
	for(;;);
}

uint32_t get_current_stack_msp(void)
{
	return task_stacks[current_task];
}

__attribute ((naked)) void change_sp_to_msp(void)
{
	__asm volatile ("BL get_current_stack_msp");
	__asm volatile ("MSR MSP, R0");
}

void enable_all_exceptions(void)
{
	uint32_t *pSHCRS = (uint32_t *)SHCRS;
	*pSHCRS |= (1<< 0);	//MEMFAULTACT
	*pSHCRS |= (1<< 1);	//BUSFAULTACT
	*pSHCRS |= (1<< 3);	//USGFAULTACT
}

void task1_handler(void)
{
	while(1)
	{
		printf("In Task1 Handler\n");
	}

}

void task2_handler(void)
{
	while(1)
	{
		printf("In Task2 Handler\n");
	}

}

void task3_handler(void)
{
	while(1)
	{
		printf("In Task3 Handler\n");
	}

}

void task4_handler(void)
{
	while(1)
	{
		printf("In Task4 Handler\n");
	}
}


//2. implement the fault handlers
void HardFault_Handler(void)
{
	printf("Exception : Hardfault\n");
	while(1);
}


void MemManage_Handler(void)
{
	printf("Exception : MemManage\n");
	while(1);
}

void BusFault_Handler(void)
{
	printf("Exception : BusFault\n");
	while(1);
}
